### ISSUE TITLE
surveyjs-react doesn't work when using google translate

### ISSUE THREAD

**Issue by joker-777** [surveyjs/survey-library#3189]
If the user has Google translate enabled on its Chrome and goes to the next page of the form it shows this error in the console and the whole form disappears.

```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insertBefore (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:10290:18)
    at insertOrAppendPlacementNode (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21222:7)
    at commitPlacement (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21183:5)
    at commitMutationEffects (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23361:11)
    at HTMLUnknownElement.callCallback (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at commitRootImpl (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23121:9)
    at unstable_runWithPriority (https://9cvi6.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at commitRoot (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22990:3)
    at performSyncWorkOnRoot (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22329:3)
    at eval (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11327:26)
    at unstable_runWithPriority (https://9cvi6.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushSyncCallbackQueueImpl (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11322:9)
    at flushSyncCallbackQueue (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11309:3)
    at discreteUpdates$1 (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22420:9)
    at discreteUpdates (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3756:12)
    at dispatchDiscreteEvent (https://9cvi6.csb.app/node_modules/react-dom/cjs/react-dom.development.js:5889:3)
````

You can test it by opening [this example](https://surveyjs.io/Examples/Library?id=navigation-default&platform=Reactjs&theme=modern) in the codesandbox, then run it in a [dedicated tab](https://9cvi6.csb.app/), right click somewhere and select "translate to ...". Then fill out the question and go to the next page. It should create this error.

**Comment by AbhishekKS** [comment]
Hi @tsv2013 ,
I can see this issue as well. I tried Arabic language. But it happens for Finnish as well. I tried out the below example in the new window.  
https://surveyjs.io/Examples/Library?id=navigation-default&platform=Reactjs&theme=modern.

**Attached are recording and console errors for your reference.**

https://user-images.githubusercontent.com/13827554/129036424-db84cc6e-8346-41ab-913b-5d09fb584c8f.mp4

**Console Error:**
![image](https://user-images.githubusercontent.com/13827554/129036519-7630f268-224e-4888-a7ef-d13181b1217e.png)

Thanks
Abhishek

**Comment by tsv2013** [comment]
Unfortunately still can't reproduce the issue. Can you switch off all chrome extensions?

**Comment by joker-777** [comment]
@tsv2013 Did you go to the next page. The error only happens after filling out the first page and then going to the next page. I just tested it in incognito Mode (no browser extensions) and definitely shows me this error.
Please use this page for testing https://9cvi6.csb.app/

**Comment by joker-777** [comment]
BTW, we had the same error with our own react code. It took me a long time to figure out the reason. It was that we used `<></>` for certain text elements where we add other text elements by condition. The solution was to use `<span></span>` instead.

**Comment by tsv2013** [comment]
Yes, I've got the error if press next page. We need to discuss this issue intarnally.

**Comment by tsv2013** [comment]
@andrew Could you take a look?

**Comment by andrewtelnov** [comment]
@joker-777 @tsv2013 It is a known issue with react and google translate. Here is the [related issue in react repo](https://github.com/facebook/react/issues/11538).
I strongly believe that facebook or google should come with the solution. It could take a lot of efforts from us to fix this issue, since we have a lot of code in react and it is not certain, what should we change in our code, since it is written absolutely correct.
We will keep this issue open and investigate it more deeply after releasing Creator V2 Beta. Right now, I personally, do not want to spend a lot of time on it, since it will be a work-around that could stop working at any moment. I believe it is better to find the reason and suggest the fix to react, since It seems to me the bug in the code of a facebook team.

Thank you,
Andrew
