### ISSUE TITLE
Cannot read properties of undefined (reading 'add') exception occurs at Survey.setSurveyEvents when passing a survey JSON to SurveyWindow

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-library#4739]
The following exception is thrown when initializing SurveyWindow with a survey JSON string:
```
const surveyJson = {
    ...
  };
function SurveySample(){
     const survey = new Model(surveyJson);
    return <SurveyWindow model={surveyJson} isExpanded= { true }/>; 
}
```
```
reactSurvey.tsx:297 Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at Survey.setSurveyEvents (reactSurvey.tsx:297:1)
    at Survey.createSurvey (reactSurvey.tsx:254:1)
    at SurveyWindow.createSurvey (reactSurveyWindow.tsx:69:1)
    at SurveyWindow.Survey [as constructor] (reactSurvey.tsx:33:1)
    at new SurveyWindow (reactSurveyWindow.tsx:8:1)
    at constructClassInstance (react-dom.development.js:14323:1)
    at updateClassComponent (react-dom.development.js:19688:1)
    at beginWork (react-dom.development.js:21611:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
```
`this.survey.onPartialSend` returns undefined at `setSurveyEvents`.

Please refer to this sample: https://plnkr.co/edit/3nC0xe7msSDE9Amb.

**Comment by andrewtelnov** [comment]
@JaneGaid Here is the code and examples for using json and model:
For using [json](https://plnkr.co/edit/fuHNlXYkgkHSlsrV)
```js
function onComplete(sender, options) {
  document.querySelector('#surveyResult').textContent = "Result JSON:\n" + JSON.stringify(sender.data, null, 3);
};
ReactDOM.render (<SurveyReact.SurveyWindow json={json} onComplete={onComplete}
  isExpanded={true}/>, document.getElementById("surveyElement"));
```

For using [model](https://plnkr.co/edit/Ras3nmyH9IXjQEsy)
```js
const survey = new Survey.Model(json);
survey.onComplete.add(function (sender) {
  document.querySelector('#surveyResult').textContent = "Result JSON:\n" + JSON.stringify(sender.data, null, 3);
});
ReactDOM.render (<SurveyReact.SurveyWindow model={survey}
  isExpanded={true}/>, document.getElementById("surveyElement"));
```
You have to set properties and event handlers in rendering React component in the first variant.
The second variant, allows you to change/set event handlers on survey model and provides more options.

Thank you,
Andrew

**Comment by JaneGaid** [comment]
@RomanTsukanov please fix the documentation topic: https://surveyjs.io/Documentation/Library?id=design-survey-create-a-simple-survey
```
function App() {
  const survey = new Model(surveyJson);

  // Render the survey inside the page
  return <Survey model={survey} />;

  // Render the survey as an expandable window
  return <SurveyWindow model={surveyJson} />;
}
```
