### ISSUE TITLE
Angular: Cannot register a component as a custom cell type for a Dropdown/Dynamic Matrix

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5977]
Original issue: T12655 - Custom Component as a column cell type for dynamic matrix?
https://surveyjs.answerdesk.io/internal/ticket/details/T12655

The `Can't create component with name: masterdata_dropdown-question and default: undefined` exception occurs on an attempt to use a custom component as a Dynamic Matrix cell type.

To reproduce the issue, run this [example](https://codesandbox.io/s/surveyjs-angular-forked-8mewwe?file=/src/app/components/creator.component.ts), add a Dropdown/Dynamic Matrix, and select a `masterdata_dropdown` cell type.

```js
import { matrixDropdownColumnTypes } from "survey-core";
import { SurveyQuestionEditorDefinition } from "survey-creator-core";

const masterData = [1, 2, 3];
ComponentCollection.Instance.add({
  name: "masterdata_dropdown",
  title: "Masterdata Dropdown",
  icon: "dropdown",
  questionJSON: {
    type: "dropdown",
    choices: ["Item 1", "Item 2", "Item 3"],
    defaultValue: "Item 1"
  }
});

Serializer.addProperty("masterdata_dropdown", {
  name: "MasterDataMenu",
  category: "general",
  visibleIndex: 3,
  choices: masterData
});
SurveyQuestionEditorDefinition.definition[
  "matrixdropdowncolumn@masterdata_dropdown"
] = {
  properties: ["MasterDataMenu"]
};
matrixDropdownColumnTypes["masterdata_dropdown"] = {};
```

The following exception occurs.
```callstack
caught Error: Can't create component with name: masterdata_dropdown-question and default: undefined
    at DynamicComponentDirective.createComponent (survey-angular-ui.js:1058:13)
    at DynamicComponentDirective.ngOnChanges (survey-angular-ui.js:1045:12)
    at DynamicComponentDirective.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1523:14)
    at callHook (core.mjs:2505:18)
    at callHooks (core.mjs:2464:17)
    at executeInitAndCheckHooks (core.mjs:2415:9)
    at refreshView (core.mjs:12003:21)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshComponent (core.mjs:13084:13)
    at refreshChildComponents (core.mjs:11778:9)
    at refreshView (core.mjs:12038:13)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
    at refreshEmbeddedViews (core.mjs:13038:17)
    at refreshView (core.mjs:12012:9)
```

**Comment by JaneSjs** [comment]
This error also occurs for the Progressbar Percentage component: T12658 - progressbar-percentage Bug (Angular)
https://surveyjs.answerdesk.io/internal/ticket/details/T12658

**Comment by andrewtelnov** [comment]
@JaneSjs It can probably not related. I mean T12658. I have fixed the original issue by this [PR](https://github.com/surveyjs/survey-library/pull/5978).
