### ISSUE TITLE
Dropdown with Lazy Loading (Angular) - The 'Cannot read properties of undefined (reading 'renderAs')' exception is thrown when clearing the selected value

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6125]
User issue: T12913 - The Cannot read proprties of undefined exception is thrown when clearing a dropdown question value
https://surveyjs.answerdesk.io/internal/ticket/details/T12913
***
[Example](https://codesandbox.io/s/surveyjs-angular-forked-xfq04y?file=/src/app/components/json.ts)

To reproduce the issue, select a Dropdown item, navigate to the next page, navigate back to the Dropdown page, and click the Clear button to remove a selected item. The following error appears in the console:
```
ERROR TypeError: Cannot read properties of undefined (reading 'renderAs')
    at SurveyStringComponent_Template (ng:///SurveyStringComponent/ɵcmp.js:16:88)

    at executeTemplate (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4800:231)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4769:163)

    at refreshComponent (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5101:165)

    at refreshChildComponents (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4711:1733)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4778:57)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshComponent (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5101:165)

    at refreshChildComponents (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4711:1733)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4778:57)

    at refreshComponent (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5101:165)

    at refreshChildComponents (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4711:1733)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4778:57)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at refreshEmbeddedViews (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5085:996)

    at refreshView (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:4774:40)

    at detectChangesInternal (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5177:265)

    at ViewRef$1.detectChanges (https://xfq04y.csb.app/node_modules/@angular/core/fesm2020/core.mjs:5438:24)

    at ElementComponent.detectChanges (https://xfq04y.csb.app/node_modules/survey-angular-ui/fesm2015/survey-angular-ui.js:956:33)

    at eval (https://xfq04y.csb.app/node_modules/survey-angular-ui/fesm2015/survey-angular-ui.js:943:16)
```

**Comment by JaneSjs** [comment]
+1 User Report
T12924 - Dropdown bug (Angular)
https://surveyjs.answerdesk.io/internal/ticket/details/T12924
