### ISSUE TITLE
Nuxt.js v3.6.1 - The Class extends value undefined is not a constructor or null exception occurs when using the 'survey-vue-ui' package and a ClientOnly survey component

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#6436]
User Issue: T13658 - Nuxt 3 "Class extends value undefined is not a constructor or null"
https://surveyjs.answerdesk.io/internal/ticket/details/T13658
***
View Demo:

Create a Nuxt v3.6.1 app, install a `survey-vue-ui` package and create a client-only survey component:
**app.vue**
```
<template>
  <div>    
    <ClientOnly>
      <Survey />
    </ClientOnly>
  </div>
</template>

<script>
import Survey from '~/components/Survey.vue'

export default {
  name: 'IndexPage',
  components: {
    Survey
  },  
}
</script>
```
**./components/Survey.vue**
```
<template>
    <Survey :survey="survey" />
  </template>
  
  <script>
  import 'survey-core/defaultV2.min.css';
  import { Model } from 'survey-core';
  import { Survey } from 'survey-vue-ui';
  
  const surveyJson = {
    elements: [{
      name: "FirstName",
      title: "Enter your first name:",
      type: "text"
    }, {
      name: "LastName",
      title: "Enter your last name:",
      type: "text"
    }]
  };
  
  export default {
    name: 'MyFirstSurvey',
    components: {
      Survey
    },
    data() {
      const survey = new Model(surveyJson);
      survey.onComplete.add((sender, options) => {
        console.log(JSON.stringify(sender.data));
      })
      return {
        survey
      }
    },
  }
  </script>
```
Build and run the application
```
npm run build
npm run dev
```
The following exception appears in a console: 
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at vue-ui.ts:7:62
    at base.ts:6:30
    at ./src/vue/base.ts (base.ts:65:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./src/vue/survey.vue?vue&type=script&lang=ts& (string.vue:16:16)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/vue/survey.vue?vue&type=script&lang=ts& (survey.vue:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/vue/survey.vue (survey.vue:1:1)
    at __webpack_require__ (bootstrap:19:1)
```

**Comment by dk981234** [comment]
Hello,

The survey-vue-ui library does not work with vue3.
We are currently implementing a UI library for vue3.
See the relevant issue: https://github.com/surveyjs/survey-library/issues/6402.

Thanks,
Dmitry
SurveyJS Team
