### ISSUE TITLE
Dynamic Panel: A custom Remove button is not applied with the `panelRemoveButtonLocation` property is set to `"right"`

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7064]
User Issue: T14815 - Dynamic Panel - Override a Remove panel button
https://surveyjs.answerdesk.io/internal/ticket/details/T14815
***
Usage scenario: register a custom remove panel button. It works if you use the default button location mode ([View CodeSandbox](https://codesandbox.io/s/surveyjs-angular-forked-lmv9q8?file=/src/app/components/survey.component.ts)).
![image](https://github.com/surveyjs/survey-library/assets/22372972/0dc04b6b-eb4a-420a-a2b8-5dd9346bc3ae)

However, a custom button is not used if you set `panelRemoveButtonLocation` to `"right"`.
[View Demo](https://codesandbox.io/s/surveyjs-angular-forked-7qhchp?file=/src/app/components/survey.component.ts)

![image](https://github.com/surveyjs/survey-library/assets/22372972/713d6306-a024-4c80-9f5f-f6ca0afa7fc4)

**Comment by JaneSjs** [comment]
@dk981234, if we have the following Remove button implementation
```
export class CustomSurveyQuestionPanelDynamicRemoveButton extends PaneldynamicAction {
  @Input() public model!: Action;

  get question() {
    return this.model.data.question;
  }

  handleClick() {
    this.question.removePanelUI(this.model.data.panel);
  }
}
AngularComponentFactory.Instance.registerComponent(
  "sv-paneldynamic-remove-btn",
  CustomSurveyQuestionPanelDynamicRemoveButton
);
```
It works when a button location is set to `bottom`.
https://codesandbox.io/s/surveyjs-angular-forked-zqq7qt?file=/package.json

However, if we change the button location to `right`, the custom Remove button implementation won't work.
https://codesandbox.io/s/surveyjs-angular-forked-59nxmj?file=/src/app/components/json.ts

```
ERROR TypeError: Cannot read properties of undefined (reading 'data')
    at get question [as question] (https://zqq7qt.csb.app/src/app/components/survey.component.ts:15:27)

    at CustomSurveyQuestionPanelDynamicRemoveButton.handleClick (https://zqq7qt.csb.app/src/app/components/survey.component.ts:19:14)

    at CustomSurveyQuestionPanelDynamicRemoveButton_Template_button_click_0_listener (ng:///CustomSurveyQuestionPanelDynamicRemoveButton.js:13:22)

    at executeListenerWithErrorHandling (https://zqq7qt.csb.app/node_modules/@angular/core/fesm2020/core.mjs:6279:8)

    at wrapListenerIn_markDirtyAndPreventDefault (https://zqq7qt.csb.app/node_modules/@angular/core/fesm2020/core.mjs:6294:149)

    at HTMLButtonElement.eval (https://zqq7qt.csb.app/node_modules/@angular/platform-browser/fesm2020/platform-browser.mjs:597:34)

    at _ZoneDelegate.invokeTask (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:406:31)

    at Object.onInvokeTask (https://zqq7qt.csb.app/node_modules/@angular/core/fesm2020/core.mjs:11361:652)

    at _ZoneDelegate.invokeTask (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:405:60)

    at Zone.runTask (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:178:47)

    at ZoneTask.invokeTask [as invoke] (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:487:34)

    at invokeTask (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:1661:18)

    at globalCallback (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:1692:29)

    at HTMLButtonElement.globalZoneAwareCallback (https://zqq7qt.csb.app/node_modules/zone.js/fesm2015/zone.js:1725:16)
```

To make it work, it is necessary to update the custom Remove button implementation.
```
export class CustomSurveyQuestionPanelDynamicRemoveButton {
  get question() {
    return this.data.question;
  }

  handleClick() {
    this.question.removePanelUI(this.data.panel);
  }
}
AngularComponentFactory.Instance.registerComponent(
  "sv-paneldynamic-remove-btn",
  CustomSurveyQuestionPanelDynamicRemoveButton
);
```
https://codesandbox.io/s/surveyjs-angular-forked-5gntnr?file=/src/app/components/survey.component.ts:726-1048

However, this doesn't look like a correct option to modify the Remove button implementation depending on a button location. What do you think?

**Comment by JaneSjs** [comment]
The updated code for a custom Remove button:
```
import {
  AngularComponentFactory,
  PaneldynamicRemoveButtonComponent
} from "survey-angular-ui";

@Component({
  selector: "app-custom-survey-question-panel-dynamic-remove-button",
  template: `
    <button
      class="sd-action sd-action--icon sd-action--negative sd-matrixdynamic__btn sd-matrixdynamic__remove-btn"
      type="button"
      title="Remove"
      (click)="handleClick()"
    >
      <svg class="sd-action__icon sv-svg-icon">
        <use href="#icon-delete"></use>
      </svg>
    </button>
  `
})
export class CustomSurveyQuestionPanelDynamicRemoveButton extends PaneldynamicRemoveButtonComponent {
  handleClick() {
    this.question.removePanelUI(this.panel);
  }
}
AngularComponentFactory.Instance.registerComponent(
  "sv-paneldynamic-remove-btn",
  CustomSurveyQuestionPanelDynamicRemoveButton
);
```
https://codesandbox.io/s/surveyjs-angular-forked-ljmpsn?file=/src/app/components/survey.component.ts
