### ISSUE TITLE
Dropdown - The 'Cannot set properties of undefined (setting 'selectedValue')' exception is thrown on an attempt to select a value after searching for a value which was not found in a list

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7114]
User Issue: T14982 - Dropdown - Error on selecting dropdown after searching a value with no matching data (Lazy Loading)
https://surveyjs.answerdesk.io/internal/ticket/details/T14982
***
```
Uncaught TypeError: Cannot set properties of undefined (setting 'selectedValue')
    at t.beforeScrollToFocusedItem (survey.core.min.js:6:744022)
    at t.changeSelectionWithKeyboard (survey.core.min.js:6:743704)
    at t.focusItemOnClickAndPopup (survey.core.min.js:6:743136)
    at t.onClick (survey.core.min.js:6:742625)
    at t.click (survey-react-ui.min.js:6:103338)
    at Object.lj (react-dom.production.min.js:223:217)
    at kj (react-dom.production.min.js:34:117)
    at nj (react-dom.production.min.js:34:171)
    at gh (react-dom.production.min.js:62:93)
    at Xg (react-dom.production.min.js:63:1)
```
To reproduce the issue, follow these steps [on our Dropdown demo](https://surveyjs.io/form-library/examples/lazy-loading-dropdown/reactjs#).

https://github.com/surveyjs/survey-library/assets/22372972/ab53e967-6f21-4408-933f-e4198c99adda

**Comment by JaneSjs** [comment]
Cannot reproduce in v1.9.112.

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-library/issues/7043
