### ISSUE TITLE
Table Of Contents - Display a special mark within a page item when a page contains errors

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7320]
User issue: T15426 - enable required panels/pages to ignore custom questions when validating
https://surveyjs.answerdesk.io/internal/ticket/details/T15426
***
Add an option to display some special mark within a page's title to inform users that a page contains errors. 
![image](https://github.com/surveyjs/survey-library/assets/22372972/673d5f25-8ee1-4564-ab5d-4806882f2dca)

**Comment by JaneSjs** [comment]
It is possible to display a special sign for a Table Of Contents page item using the Markdown feature. 

[View CodeSandbox](https://codesandbox.io/s/unruffled-golick-4wf3fs?file=/src/SurveyComponent.jsx).

Here are main implementation steps.

* Use the [page.navigationTitle](https://surveyjs.io/form-library/documentation/api-reference/page-model#navigationTitle) to specify the caption which appears within Table Of Contents.
* Register a custom page property. The property would indicate whether or not a page navigation title contains an error mark. The property will be further used within the `survey.onTextMarkdown` callback.
```js
import { Serializer } from "survey-core";

Serializer.addProperty("page", {
  name: "errorMarkExists",
  type: "boolean",
  default: false
});
```
* Implement the [survey.onTextMarkdown](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onTextMarkdown) function to add a special character (`#`) to a page's navigtion title if a page contains errors.
```js
survey.onTextMarkdown.add((sender, options) => {
    const el = options.element;
    console.log(
      "name: " +
        options.name +
        ", text: " +
        options.text +
        ", element type: " +
        el.getType()
    );
    if (!el || el.getType() !== "page") return;

    if (options.name === "navigationTitle") {
      const page = el;
      const pi = page.getProgressInfo();
      const isCompleted = pi.questionCount === pi.answeredQuestionCount;
      let hasErrors = false;
      const questions = page.questions;
      for (let i = 0; i < questions.length; i++) {
        if (questions[i].errors.length > 0) {
          hasErrors = true;
          break;
        }
      }
      let html = "";
      if (hasErrors && !el.errorMarkExists) {
        el.errorMarkExists = true;
      } else if (!hasErrors && el.errorMarkExists) {
        el.errorMarkExists = false;
      }

      if (el.errorMarkExists) {
        if (options.text.indexOf("#") < 0) {
          html = options.text + "#";
        } else {
          html = options.text;
        }
      } else {
        html = options.text.replace("#", "");
      }

      if (!isCompleted) {
        html = "<strong>" + html + "</strong>";
      }
      options.html = html;
    }
});
```
Now, when a user attempts to complete a survey which contains errors, an error indicator appears within Table Of Contents.
![image](https://github.com/surveyjs/survey-library/assets/22372972/81d7a0f1-79fc-46c3-bff6-9d52a9d6a07c)

**Comment by JaneSjs** [comment]
With v1.11.14, it is possible to override an item component template for a Table of Contents.

The following demo shows how to implement a custom TOC item and:
* Display information about the answered and total questions per page.
* Highlight a TOC item with Red/Yellow/Green depending on the number of answered questions.
![image](https://github.com/user-attachments/assets/d31ddb0f-e565-47cf-943e-f75a4c764e35)

Follow these steps:

1. Implement a component that renders item markup.
The component accepts the item configuration object as a prop. You can use its item property to access the IAction which corresponds to the current page item within a TOC. Use this object to retrieve information about the current page and its answered and total question count.

2. Register the component so that it can be accessed by name.

In React and other JS applications, register the component in ReactElementFactory as shown in the CustomTocItem.jsx file. In Angular, register the component in AngularComponentFactory as shown in the toc-custom-item.component.ts file. In Vue, implement the CustomTocItem component as shown in the CustomTocItem.vue file and register it within application components.

3. Obtain the Table of Contents navigation element and set the itemComponent property to the custom component name.
```
survey.findLayoutElement("toc-navigation").data.listModel.itemComponent = "sv-custom-toc-item";
```
* [View Demo for JS](https://codesandbox.io/p/sandbox/z4nvh5)
* [View Demo for React](https://codesandbox.io/p/sandbox/pf3qx7)
* [View Demo for Angular](https://codesandbox.io/p/sandbox/fjgly6)
* [View Demo for Vue](https://codesandbox.io/p/sandbox/qwvgcl)

**Comment by forat98** [comment]
@JaneSjs  i'm try to use  above  code but the Property 'locOwner' does not exist on type 'ILocalizableOwner' return this.model.owner.locOwner 
also this  Property 'getPageByName' does not exist on type 'ILocalizableOwner' 
- return this.survey.getPageByName(pageName)

**Comment by JaneSjs** [comment]
Hi @forat98,
I tested this [React](https://codesandbox.io/p/sandbox/pf3qx7) and [Angular](https://codesandbox.io/p/sandbox/fjgly6) demos. A table of contents with a custom item component appears correctly.

Would you clarify which JS platform you're using and which example you tried?

**Comment by forat98** [comment]
i'm use angular platform , but see even if in your demo you see return this.model.owner.**locOwner**; "Property 'locOwner' does not exist on type 'ILocalizable Owner'.typescript(2339) "

**Comment by JaneSjs** [comment]
Hi @forat98,
Thank you for the update. To solve the issue, update the `toc-custom-item.component.ts` as follows:
```
get survey() {
   return this.model.owner['locOwner'];
}
```
Meanwhile, take note that this code uses non-documented API. We'll consider adding a public API for implelenting a custom item component. 

Thank you

**Comment by forat98** [comment]
I'm encountering an issue when trying to create a custom component in my Angular application using SurveyJS. The error message is as follows: 

Can't create component with name: sv-custom-toc-item and default: undefined  
    at DynamicComponentDirective.createComponent (survey-angular-ui.js:214:19)  
    at DynamicComponentDirective.ngOnChanges (survey-angular-ui.js:199:18)  
    at DynamicComponentDirective.rememberChangeHistoryAndInvokeOnChangesHook  
    
    It occurs when I try to use `sv-custom-toc-item`. Could you provide guidance on what might be causing this issue? I'm using the latest version of SurveyJS

**Comment by JaneSjs** [comment]
Hi @forat98,
Please refer to the following demo for Angular: [View CodeSandbox](https://codesandbox.io/p/sandbox/qmfjnh).

**Comment by JaneSjs** [comment]
Hi Everyone,
With v2.5.35, you can register a custom TOC item component and set the `SurveyModel.tocItemComponent` property to the component's name. Within a custom component, access the corresponding page and survey instances via the `page` and `survey` props. 

[View Demo](https://plnkr.co/edit/Q9U8xTmRAz3SWl3V)
