### ISSUE TITLE
[Knockout] The Uncaught TypeError: Cannot read properties of null (reading 'forEach') exception is thrown when a Collapsed Panel Contains a Multi-Select Matrix

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#7355]
[View Plunker](https://plnkr.co/edit/EKSZ7B6yi1wKAtDR)
If a panel is collapsed by default (`"state": "collapsed"`), the following exception appears:
```
survey.core.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at t.collectNestedQuestonsInRows (survey.core.min.js:6:451434)
    at t.collectNestedQuestionsCore (survey.core.min.js:6:451325)
    at t.collectNestedQuestions (survey.core.min.js:6:304046)
    at t.onHidingContent (survey.core.min.js:6:450917)
    at survey.core.min.js:6:847134
    at Array.forEach (<anonymous>)
    at t.notifyStateChanged (survey.core.min.js:6:847104)
    at t.set (survey.core.min.js:6:238940)
    at e.setValue (survey.core.min.js:6:62862)
    at e.valueToObj (survey.core.min.js:6:86450)
```
It works in React ([demo](https://codesandbox.io/s/eloquent-grothendieck-wtllqp?file=/src/json.js:20-669)).

**Comment by andrewtelnov** [comment]
@JaneSjs It has been fixed in v1.9.117. Here is [the updated example](https://plnkr.co/edit/zeb0uyMBFBkX27Vk).
I will add a unit test on it.
